name: process-in-process Docker image

on:
  repository_dispatch:
    types: [pip-gdb-test-ok]

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        distro: ${{ github.event.client_payload.distros }}
        pip_version: ${{ github.event.client_payload.pip_versions }}

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ github.event.client_payload.platforms }}
          file: package/docker/process-in-process/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USER }}/process-in-process:${{ matrix.pip_version }}.HEAD-${{ matrix.distro }}
          build-args: |
             DOCKER_BASE=${{ secrets.DOCKERHUB_USER }}/pip-prep:${{ matrix.distro }}
             SRC_REPO=https://github.com/${{ github.repository }}
             SRC_REF=${{ github.ref }}
             PIP_VERSION=${{ matrix.pip_version }}
          push: true
